name: Node.js CI

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  
jobs:
    build:
  
      runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [14.x, 16.x, 'lts/*']  
  
      steps:
      - uses: actions/checkout@v3  # Update to the latest version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3   # Update to the latest version
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change to API directory
        run: cd api      # Change to the api directory
      - name: Install dependencies
        run: npm ci      # Install dependencies
      - name: Run tests
        run: npm test    # Run tests
